baseURL = 'https://blog.kagamino.dev/'
copyright = "{year}"                   # To make 2007 - 2022. Just add before {year} example: 2007 - {year}
languageCode = 'en-us'
theme = 'lowkey'
title = "Kagamino's Blog"
enableRobotsTXT = true

# List Config
summaryLength = 15
paginate = 5

[markup.highlight]
codeFences = true
guessSyntax = false
hl_Lines = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = false
tabWidth = 4
noClasses = true
style = "monokai"

[outputs]
section = ["html", "rss"]

[author]
email = 'martin@lehoux.net'
name = "Martin 'Kagamino' Lehoux"
