[[main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[main]]
identifier = "posts"
name = "Posts"
url = "/posts"
weight = 2


# Social Media Configuration

[[social]]
identifier = "linkedin"
name = "LinkedIn"
url = "https://www.linkedin.com/in/martin-lehoux/"
weight = 1

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/martinlehoux"
weight = 2
