[project]
name = "kagamino-blog"
version = "0.1.0"
description = "Tooling for blog scripts"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "altair>=6.2.1",
    "marimo>=0.23.10",
    "pandas>=3.0.3",
    "psycopg[binary]>=3.2.9",
    "pytest>=8.4.2",
    "pytest-benchmark>=5.1.0",
]

[tool.pytest.ini_options]
python_files = "tests.py test_*.py"
